#=============================================================================================

# Learn-React
# Github: https://github.com/RemainAplomb/Learn-React

#=============================================================================================

# 1. React Tutorial for Beginners (by Mosh)
# Folder name: react-app-mosh
# React Environment: vite@4.1.0
# Tutorial by: Programming with Mosh
# Retrieved from: https://www.youtube.com/watch?v=SqcY0GlETPk

#-------------------------------------------------------------------
# Install the project's dependencies
# You must be in react-app-mosh directory
npm-install:
	npm install

# Open the project in vscode
# You must be in react-app-mosh directory
open-react-app-mosh:
	code .

# Run server
# You must be in react-app-mosh directory
# This will run the website in localhost
npm-run-dev:
	npm run dev

# Install Bootstrap
npm-bootstrap:
	npm i bootstrap@5.2.3

#=============================================================================================

